# mkdocs.yml
site_name: ruhmi-framework-mcu-documents
site_url: https://Masamitsu1025.github.io/ruhmi-framework-mcu-document/
site_description: Comprehensive technical documentation for My Project
site_author: Masamitsu Muratani

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
#    - navigation.tabs.sticky
#    - navigation.sections
    - search.suggest         # Enable search suggestions
    - search.highlight       # Highlight search terms
    - content.code.copy      # Copy button for code blocks
    - content.tabs.link      # Linkable content tabs
    - content.action.edit    # Show "Edit this page" button

plugins:
   - search
#   - linkcheck:
#      fail_on_warning: true
   - git-revision-date-localized:
      enable_creation_date: true
  - htmlproofer:
      validate_external_urls: true
      raise_error: true

nav:
  - Home: README.md
  - Installation guide: install/README.md
  - How to scripts: scripts/README.md
  - Handling optput source code: runtime_api.md
  - API Reference: mera_api.md
  - error list: error_list.md
  - FAQ & Tips: tips.md

