# mkdocs.yml
site_name: ruhmi-framework-mcu-test
site_url: https://masamitsu1025.github.io/ruhmi-framework-mcu-document/
site_description: Project documentation
site_author: Masamitsu Muratani

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest         # Enable search suggestions
    - search.highlight       # Highlight search terms
    - content.code.copy      # Copy button for code blocks
    - content.tabs.link      # Linkable content tabs
    - content.action.edit    # Show "Edit this page" button
nav:
  - Home: index.md
  - Installation guide: ..\install\README.md
  - Sample scripts for CLI: ..\scripts\README.md
  - API Reference: api-reference.md
  - FAQ: faq.md

