name: Collect READMEs and Deploy with MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write   # gh-pages へ push するために必須

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # サブモジュールに README がある場合は↓を有効化
        # with:
        #   submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip (Windows)
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Collect READMEs into docs/
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          & "scripts\collect-readmes.ps1" -Clean 


      # docs 以下の .md をリンクチェック（再帰、GETで厳しめ）
      - name: Link check (markdown)
        run: python -m mkdocs_linkcheck docs --recurse --method get

#      - name: Build (option)
#        run: python -m mkdocs build --strict
        # --strict: 設定/リンク等の警告をエラー化（不要なら外してください）

      - name: Deploy to GitHub Pages
        run: python -m mkdocs gh-deploy --force
        