name: Collect READMEs and Deploy with MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write   # gh-pages へ push するために必須

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # サブモジュールに README がある場合は↓を有効化
        # with:
        #   submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip (Windows)
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 任意: mkdocs-linkcheck を使うなら mkdocs.yml に plugins を追加してください
      # plugins:
      #   - search
      #   - linkcheck:
      #       fail_on_warning: true

- name: Debug: show tree (robust)
  shell: pwsh
  run: |
    $ErrorActionPreference = 'Continue'
    Write-Host "PWD before: $PWD"
    if ($env:GITHUB_WORKSPACE) { Set-Location $env:GITHUB_WORKSPACE }
    Write-Host "PWD after : $PWD"

    # まず主要ファイルの存在確認
    Write-Host "mkdocs.yml exists? " (Test-Path "mkdocs.yml")
    Write-Host "scripts\\collect-readmes.ps1 exists? " (Test-Path "scripts\\collect-readmes.ps1")
    Write-Host "docs exists? " (Test-Path "docs")

    # 失敗しにくい列挙（エラーは無視して続行）
    Get-ChildItem -Path . -Recurse -Force -File -ErrorAction SilentlyContinue |
      ForEach-Object { $_.FullName }

    # 直近の PowerShell エラー内容も出力（あれば）
    if ($Error.Count -gt 0) {
      Write-Host "---- Captured errors ----" -ForegroundColor Yellow
      $Error | Select-Object -First 5 | ForEach-Object { $_.ToString() | Write-Host }
    }


      - name: Collect READMEs into docs/
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          & "scripts\collect-readmes.ps1" -Clean

      - name: Build (optional)
        run: mkdocs build --strict
        # --strict: 設定/リンク等の警告をエラー化（不要なら外してください）

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        