name: Collect READMEs and Deploy with MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest   # Windows ランナーを使用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect READMEs into docs/
        shell: pwsh
        run: |
          ./scripts/collect-readmes.ps1 -Clean

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

