name: Build & Deploy with MkDocs (gh-pages, no docs commit)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      # ここで docs/ を CI 内だけで生成（ファイル名は変えず）
      - name: Collect md & images into docs/
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          # あなたのスクリプト名に合わせてください（例：collect-all.ps1）
          & "scripts\collect-readmes.ps1" -Clean

      # 生成結果をログに出す（確認用）
      - name: Show docs tree
        shell: pwsh
        run: |
          Write-Host "=== docs/ tree ==="
          if (Test-Path docs) {
            Get-ChildItem docs -Recurse |
              Select-Object FullName, Length |
              Format-Table -AutoSize
          } else {
            Write-Error "docs/ not found"
          }

      # （任意）生成した docs/ を artifact として保存すると、後でダウンロード確認できます
      - name: Upload docs as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: docs-generated
          path: docs/**

      # ビルド & デプロイ（同じ Python で実行）
      - name: Build (strict)
        run: python -m mkdocs build #--strict

      - name: Deploy to GitHub Pages
        run: python -m mkdocs gh-deploy --force
